# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "base"

  config.vm.define :ansible do |node|
    node.vm.box = "generic/ubuntu2110"
    node.vm.network :forwarded_port, guest: 22, host: 2211, id: "ssh"
    node.vm.network :forwarded_port, guest: 8080, host: 8011, id: "http"
    node.vm.network :private_network, ip: "192.168.17.1"
    node.vm.synced_folder "./ansible", "/etc/ansible"
    node.vm.synced_folder "../.ssh", "/home/vagrant/keys"

    node.vm.provision "shell", inline: <<-SHELL
      apt-get update
      # apt-get install -y bzip2-devel git patch gcc openssl-devel python3-pip
      apt-get install -y python3-pip
      # add-apt-repository --yes --update ppa:ansible/ansible
      /usr/bin/pip install ansible
      echo 'PATH=/usr/bin:$PATH' >> ~/.bashrc
      cp -p /home/vagrant/keys/my_key_pair /root/.ssh/id_rsa
      chmod 600 /root/.ssh/id_rsa
      chown root:root /root/.ssh/id_rsa
    SHELL
  end

  config.vm.define :jenkins do |node|
    node.vm.box = "generic/ubuntu2110"
    node.vm.network :forwarded_port, guest: 22, host: 2212, id: "ssh"
    node.vm.network :forwarded_port, guest: 8080, host: 8012, id: "http"
    node.vm.network :private_network, ip: "192.168.17.2"
    node.vm.synced_folder "../.ssh", "/home/vagrant/key"

    node.vm.provision "shell", inline: <<-SHELL
      cat /home/vagrant/key/my_key_pair.pub >> /home/vagrant/.ssh/authorized_keys
    SHELL
  end
end