# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "base"

  config.vm.define :ansible do |node|
    node.vm.box = "generic/ubuntu2110"
    node.vm.network :forwarded_port, guest: 22, host: 2211, id: "ssh"
    node.vm.network :forwarded_port, guest: 8080, host: 8011, id: "http"
    node.vm.network :private_network, ip: "192.168.17.1"
    node.vm.synced_folder "./ansible_conf", "/etc/systemd/system"

    node.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install software-properties-common
      add-apt-repository --yes --update ppa:ansible/ansible
      apt-get install ansible
    SHELL
  end

  config.vm.define :jenkins do |node|
    node.vm.box = "generic/ubuntu2110"
    node.vm.network :forwarded_port, guest: 22, host: 2212, id: "ssh"
    node.vm.network :forwarded_port, guest: 8080, host: 8012, id: "http"
    node.vm.network :private_network, ip: "192.168.17.2"
  end
end